server:
  port: 8066

# 存储 DataAgent 业务数据的数据库，并非Agent分析数据的来源
spring:
  elasticsearch:
    uris: http://192.168.2.26:9200
    username: elastic
    password: Elastic_pwcyBZ
  datasource:
    url: ${DATA_AGENT_DATASOURCE_URL:jdbc:mysql://8.156.74.119:3306/ai_assistant_agent?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${DATA_AGENT_DATASOURCE_USERNAME:root}
    password: ${DATA_AGENT_DATASOURCE_PASSWORD:StrongRootPwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      continue-on-error: true
      separator: ;
      encoding: utf-8
  ai:
    vectorstore:
      type: elasticsearch
      elasticsearch:
        index-name: data-agent-knowledge
        similarity: cosine
        dimensions: 1024   # 和 embedding 模型一致
    alibaba:
      data-agent:
        vector-store:
          table-topk-limit: 10
          table-similarity-threshold: 0.2
          default-topk-limit: 8
          default-similarity-threshold: 0.4
        llm-service-type: stream
        code-executor:
          # 运行Python代码的环境（生产环境建议使用docker，不建议使用local）
          code-pool-executor: local
          # Python执行的最大重试次数
          python-max-tries-count: 5
        file:
          type: local
          path-prefix: data-agent
          # 当前目录下不要用点， ./uploads win下拼接完整格式路径会解析不了，比如 data-agent/./uploads win识别不了
          path: uploads
          url-prefix: /uploads
          imageSize: 2097152
          oss:
            access-key-id: ${OSS_ACCESS_KEY_ID:}
            access-key-secret: ${OSS_ACCESS_KEY_SECRET:}
            endpoint: ${OSS_ENDPOINT:}
            bucket-name: ${OSS_BUCKET_NAME:}
            custom-domain: ${OSS_CUSTOM_DOMAIN:}
        max-sql-retry-count: 5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

mybatis:

  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 日志配置
logging:
  # 日志文件路径配置
  file:
    path: logs
    name: logs/data-agent.log
  # 日志级别配置
  level:
    root: INFO
    com.alibaba.cloud.ai.dataagent: INFO
    com.alibaba.cloud.ai.dataagent.service: INFO
    com.alibaba.cloud.ai.dataagent.workflow.node: INFO
    com.alibaba.cloud.ai.dataagent.workflow.dispatcher: INFO
    com.alibaba.cloud.ai.dataagent.service.classifier: INFO
    com.alibaba.cloud.ai.dataagent.controller: INFO
    com.alibaba.cloud.ai.mapper: DEBUG
    org.springframework.jdbc: INFO
    org.springframework.web: INFO
    org.mybatis: INFO
  # 日志输出格式配置
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
